CREATE TABLE IF NOT EXISTS receivers (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
  id SERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS boxes (
  id SERIAL PRIMARY KEY,
  date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  weight NUMERIC NOT NULL,
  boxes_count INTEGER DEFAULT 1,
  receiver_id INTEGER REFERENCES receivers(id),
  product_id INTEGER REFERENCES products(id),
  comment TEXT
);
